### ISSUE TITLE
Move into path does not work on https://i.jpillora.com/

### ISSUE THREAD

**Issue by corneliusludmann** [jpillora/installer#9] opened 2020-10-07 08:15 UTC
When I run https://i.jpillora.com/chisel!, `move-to-path` is false despite the `!` at the end of the URL. See:

![image](https://user-images.githubusercontent.com/24960040/95304985-b0834e80-0885-11eb-8038-a85793edb35c.png)

When I run the latest version from master on my own it seems to work. Could it be that there is an issue with your installation?

**Comment by jpillora** [comment] 2020-10-07 10:22
Strange works for me
What browser are you using?

**Comment by corneliusludmann** [comment] 2020-10-07 10:25
It's Google Chrome Version 85.0.4183.121 (Official Build) (64-bit) on Arch Linux.

It also happens with `curl`. See: https://community.gitpod.io/t/chisel-only-works-successfully-once-i-have-no-idea-why/1924

**Comment by jpillora** [comment] 2020-10-07 10:30
Ahhhhh, confirmed the bug. Installer caches the resulting script, caching the move settings. Will fix 👍

**Comment by jpillora** [comment] 2020-10-07 10:48
Fixed in https://github.com/jpillora/installer/commit/55f50710c542a5a778a134c971d6742713faaa37

**Closed by jpillora** 2020-10-07 10:48 UTC
Labels: bug
